repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
    - id: bandit
      exclude: src/tests/|scripts
      args:
        - -s
        - B311
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    language_version: python3.12
    args:
      - --line-length=120
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args:
      - --max-line-length=120
      - --ignore=E203,W503
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
  - id: mypy
    exclude: scripts
    language_version: python3.12
